### ISSUE TITLE
garbled shared-files.tar.gz again

### ISSUE THREAD

**Issue by perlancar** [yanick/Dist-Zilla-Plugin-ShareDir-Tarball#1]
Hi Yanick :)

I'm experiencing [RT#90536](https://rt.cpan.org/Public/Bug/Display.html?id=90536) again. This time when I'm converting my dist [Ledger-Examples](https://github.com/perlancar/perl-Ledger-Examples) from ShareDir to ShareDir::Tarball. I do have a UTF8 text file containing non-Latin character in share/examples/extra-bench-basic.iod. Build process output:

```
...
[@Filter/Test::Compile] share/shared-files.tar.gz has 'bytes' encoding, skipping...

Wide character in print at /home/s1/perl5/perlbrew/perls/perl-5.18.4/lib/site_perl/5.18.4/Archive/Tar.pm line 1376.

Wide character in print at /home/s1/perl5/perlbrew/perls/perl-5.18.4/lib/site_perl/5.18.4/Archive/Tar.pm line 1376.

Wide character in print at /home/s1/perl5/perlbrew/perls/perl-5.18.4/lib/site_perl/5.18.4/Archive/Tar.pm line 1376.

Wide character in print at /home/s1/perl5/perlbrew/perls/perl-5.18.4/lib/site_perl/5.18.4/Archive/Tar.pm line 1376.

[@Filter/@Filter/MakeMaker] updating contents of Makefile.PL in memory
...
```

Just letting you know first. I'm fiddling with Archive::Tar too.

**Comment by yanick** [comment]
Hi!

For what it's worth, I did `dzil build` on the repo you gave, and it's building fine for me. And I just updated to the latest Dist::Zilla too. Weeeird...

**Comment by perlancar** [comment]
Yup, I switched back to DZP:ShareDir to release IOD-Examples 0.14 to avoid breaking the tests of Config-IOD & Config-IOD-Parser. Ok, I've tested again today on my laptop after updating all CPAN modules (using cpan-outdated, should've done this before sending my first report). The build process still outputs the "wide character in print" warning and the shared-files.tar.gz is still corrupt:

% tar tfz IOD-Examples-0.14/share/shared-files.tar.gz 
examples/multival.iod
examples/dir-merge-self.iod
examples/dirsyntax.iod.json
examples/dir-include.iod
examples/empty-section.iod.json
examples/comment.iod
examples/section.iod.json
examples/invalid-encoding-unknown.iod
examples/encoding-base64.iod.json
examples/nested-section.iod
examples/comment.iod.json
examples/key.iod.json
examples/encoding-hex.iod
examples/invalid-dir-unknown.iod
examples/dir-include.iod.json
examples/extra-bench-basic-compat.iod
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

The file examples/extra-bench-basic-compat.iod does indeed contain Unicode character, so this is related to encoding.

**Comment by perlancar** [comment]
OK, found the problem. You need to add file to the tar archive using the file's encoded_content() instead of content(). PR#2

**Comment by perlancar** [comment]
D'oh, I just realized that I first mentioned Ledger-Examples, when what I meant was IOD-Examples. The former doesn't contain non-ASCII files so the problem doesn't surface. Sorry about that.

**Comment by perlancar** [comment]
Thanks for releasing an update that fixes this problem. Anyhow, I also just released Dist::Zilla::Plugin::ShareDir::Clean, for some cases that might be more appropriate than using shared-files.tar.gz.

**Comment by yanick** [comment]
Heh. Glad the problem is solved. That was a tricky one. :-)

And :+1: for DZP::ShareDir::Clean.
